from typing import Any, Optional

from pydantic import BaseModel, Field


# ============================================================
# User's Dataset Requirement
# ============================================================

class DatasetRequirement(BaseModel):
    """
    Structured representation of what the user wants.
    Gemini will convert the natural-language request into this.
    """

    raw_request: str

    # General dataset characteristics
    modality: Optional[str] = None
    domain: Optional[str] = None
    task: Optional[str] = None

    # Size / quantity requirements
    target_size_bytes: Optional[int] = None
    target_samples: Optional[int] = None

    # Desired file/data formats
    formats: list[str] = Field(default_factory=list)

    # Required classes/categories
    classes: list[str] = Field(default_factory=list)

    # Required columns for tabular datasets
    columns: list[str] = Field(default_factory=list)

    # Additional filtering requirements
    filters: dict[str, Any] = Field(default_factory=dict)

    # Search terms Gemini generates for dataset discovery
    search_queries: list[str] = Field(default_factory=list)

    model_config = {"extra": "ignore"}


# ============================================================
# Dataset Found on an MCP Server
# ============================================================

class DatasetCandidate(BaseModel):
    """
    Represents one dataset returned by one of the
    connected MCP servers.
    """

    source: str

    # Platform-specific dataset identifier
    dataset_id: str

    name: Optional[str] = None

    description: Optional[str] = None

    downloads: int = 0

    likes: int = 0

    # Additional information returned by the MCP server
    metadata: dict[str, Any] = Field(default_factory=dict)


# ============================================================
# Dataset Processing Instructions
# ============================================================

class TransformationPlan(BaseModel):
    """
    Instructions for processing the downloaded dataset.

    Gemini decides WHAT the user needs.
    Python processing code decides HOW to perform it.
    """

    # Target output size
    target_size_bytes: Optional[int] = None

    # Number of samples/records/files requested
    target_samples: Optional[int] = None

    # Classes/categories to keep
    classes: list[str] = Field(default_factory=list)

    # CSV/tabular columns to keep
    columns: list[str] = Field(default_factory=list)

    # Filtering conditions
    filters: dict[str, Any] = Field(default_factory=dict)

    # Final packaging format
    output_format: str = "zip"


# ============================================================
# Complete DataR² Plan
# ============================================================

class DatasetPlan(BaseModel):
    """
    Complete plan generated by DataR² after:
    
    1. Understanding the user's request
    2. Searching the available MCP servers
    3. Selecting the best dataset
    4. Deciding what transformations are required
    """

    requirement: DatasetRequirement

    # Dataset selected from the available sources
    selected_dataset: Optional[DatasetCandidate] = None

    # Processing instructions
    transformation: TransformationPlan

    # Explanation for why the dataset was selected
    reasoning: str = ""
